# Generated by Django 4.0 on 2021-12-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
