# Generated by Django 4.0 on 2021-12-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0002_alter_productcategory_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
