# Generated by Django 4.0 on 2021-12-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
    ]
