# Generated by Django 4.0 on 2021-12-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0006_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=250),
        ),
    ]
